[package]
name = "stream_html_selector"
version = "0.1.0"
authors = ["Corentin Jechoux <corentinway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
